/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Local username/password login
         * @description Issues a 24 h JWT. Local password login is disabled for everyone —
         *     with no breakglass — while an OIDC provider is active or
         *     `DISABLE_LOCAL_AUTH=true`; SSO logins go through
         *     `/api/auth/oidc/login` instead. Failed attempts are rate-limited
         *     per IP.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out (revoke the presented JWT)
         * @description Blacklists the presented token's JTI until its natural expiry.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the JWT
         * @description Issues a fresh 24 h token and revokes the presented one.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active auth providers (public)
         * @description No-secret projection of the configured auth providers, consumed by the
         *     login page to decide which sign-in options to render.
         */
        get: operations["listAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start the OIDC SSO flow (browser redirect)
         * @description Redirects the browser to the configured IdP's authorization endpoint.
         *     Not an API call — open in a browser.
         */
        get: operations["oidcLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OIDC redirect URI (browser redirect)
         * @description Completes the code exchange, provisions/looks up the user, and
         *     redirects back to the app with the JWT in the URL fragment. Called by
         *     the IdP, not by API clients.
         */
        get: operations["oidcCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oidc/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * RP-initiated OIDC logout (browser redirect)
         * @description Revokes the local session (an optional Bearer token is read from the
         *     request itself) and redirects to the IdP's end-session endpoint, which
         *     then returns to the app.
         */
        get: operations["oidcLogout"];
        put?: never;
        /**
         * OIDC back-channel logout (IdP to server)
         * @description OpenID Connect Back-Channel Logout 1.0. The IdP POSTs a signed
         *     `logout_token`; the matching user's JWTs are revoked. Server-to-server
         *     only — never called by browsers or API clients.
         */
        post: operations["oidcBackchannelLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a user
         * @description `{id}` resolves as UUID → username → search term. The user themselves
         *     and admins/superadmins receive the full profile; other authenticated
         *     users get the limited projection (no email, role, or timestamps).
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a user's profile
         * @description Only the user themselves or an admin/superadmin may update a profile.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's API keys */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create an API key
         * @description Returns the plaintext `jrag_…` key **once**; only a bcrypt hash is
         *     stored. Limited to 10 keys per user.
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one of the caller's API keys */
        delete: operations["deleteApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all agents (admin UI) */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or replace an agent
         * @description The request JSON is stored verbatim (unknown fields are preserved);
         *     the backend only validates that the body `id` matches the URL and
         *     that `name` and `model` are present.
         */
        put: operations["upsertAgent"];
        post?: never;
        /**
         * Delete an agent (superadmin only)
         * @description Refused with 409 while any widget still references the agent.
         */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all widgets (admin UI) */
        get: operations["listWidgets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/widgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public widget config (consumed by widget.js)
         * @description **Public.** Reduced projection for the embedded widget: presentation
         *     fields come from the widget, brain fields (model, start prompt, rules,
         *     token cap) from its linked agent. Secrets and admin-only fields are
         *     never included.
         */
        get: operations["getPublicWidgetConfig"];
        /**
         * Create or replace a widget
         * @description The request JSON is stored verbatim (unknown fields are preserved);
         *     the backend validates the id match, `name`, `status`, and that
         *     `config` is present.
         */
        put: operations["upsertWidget"];
        post?: never;
        /** Delete a widget (superadmin only) */
        delete: operations["deleteWidget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/widgets/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Widget chat (public, rate-limited)
         * @description **Public.** Chat endpoint used by the embedded widget. The model and
         *     token cap come from the widget's linked agent — never from the
         *     client. Rate-limited to 30 requests/minute per IP. With
         *     `stream: true` the response is a Server-Sent-Events stream.
         */
        post: operations["widgetChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available upstream models
         * @description Accepts a JWT **or** a `jrag_` API key. Sorted by display name.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat completion (authenticated)
         * @description Accepts a JWT **or** a `jrag_` API key. Model and token cap are taken
         *     from the request body. With `stream: true` the response is a
         *     Server-Sent-Events stream.
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description No-secret projection of an auth provider, for the login page. */
        PublicProvider: {
            id: string;
            /** @example oidc */
            type: string;
            name: string;
        };
        ModelInfo: {
            id: string;
            name: string;
            ownedBy: string;
            /**
             * Format: int64
             * @description Unix timestamp.
             */
            created: number;
        };
        Error: {
            error: string;
        };
        LoginResponse: {
            /** @description JWT, valid 24 h. */
            token: string;
            user: {
                id: string;
                username: string;
                role: components["schemas"]["Role"];
                /** @description How this account authenticates (e.g. local, oidc). Empty on refresh. */
                authMethod: string;
            };
        };
        /** @enum {string} */
        Role: "user" | "admin" | "superadmin";
        /** @description Full profile — returned to the user themselves and to admins. */
        User: {
            id: string;
            username: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Limited projection — returned to other authenticated users. */
        UserLimited: {
            id: string;
            username: string;
            firstName?: string;
            lastName?: string;
        };
        ApiKey: {
            id: string;
            name: string;
            /**
             * @description First 13 characters of the key, for display.
             * @example jrag_9f86d081
             */
            keyPrefix: string;
            /** Format: date-time */
            lastUsedAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description Stored verbatim as JSONB — fields beyond the ones listed here (rules,
         *     tools, knowledge, …) are preserved untouched.
         */
        Agent: {
            /** @description Must match the `{id}` in the URL on PUT. */
            id: string;
            name: string;
            /** @description Upstream model id this agent runs on. */
            model: string;
            systemPrompt?: string;
            maxTokens?: number;
            rules?: components["schemas"]["WidgetRule"][];
        } & {
            [key: string]: unknown;
        };
        WidgetRule: {
            text?: string;
            enabled?: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Stored verbatim as JSONB — fields beyond the ones listed here are
         *     preserved untouched. `agentId` links the widget to the agent that
         *     provides its brain.
         */
        Widget: {
            /** @description Must match the `{id}` in the URL on PUT. */
            id: string;
            agentId?: string;
            name: string;
            /** @enum {string} */
            status: "active" | "paused";
            /** @description Lucide icon name (mapped to Material Symbols for the public config). */
            icon?: string;
            routing?: string;
            /** @description Legacy model id, used only by widgets not yet linked to an agent. */
            knowledgeBaseId?: string;
            config: {
                title?: string;
                greeting?: string;
                accentColor?: string;
                position?: string;
                templates?: string[];
                /** @description Legacy system prompt (agent takes precedence). */
                startPrompt?: string;
                /** @description Legacy rules (agent takes precedence). */
                rules?: components["schemas"]["WidgetRule"][];
                feedbackButtons?: boolean;
                /** @description Legacy token cap (agent takes precedence). */
                maxTokensPerAnswer?: number;
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** @description Reduced projection consumed by the embedded widget.js. */
        WidgetPublicConfig: {
            id: string;
            /** @enum {string} */
            status: "active" | "paused";
            /** @description Resolved model id (from the linked agent, or legacy field). */
            knowledgeBaseId: string;
            routing: string;
            title: string;
            greeting: string;
            accentColor: string;
            position: string;
            /** @description Material Symbols icon name. */
            icon: string;
            templates: string[];
            /** @description Texts of the enabled rules only. */
            rules: string[];
            startPrompt: string;
            feedbackButtons: boolean;
            /** @description Present only when the resolved token cap is > 0. */
            maxTokens?: number;
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "user" | "assistant";
            content: string;
        };
        ChatResponse: {
            reply: string;
            /** @description Upstream finish reason (e.g. stop, length). */
            finishReason: string | null;
        };
    };
    responses: {
        /** @description Malformed request or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, expired, or revoked credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but the caller's role does not permit this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No resource with this id. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error (details are sanitized). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The upstream model endpoint failed or returned an unreadable response. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description KI_API_KEY is not configured on the backend. */
        NotConfigured: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description User UUID, username, or search term. */
        UserID: string;
        AgentID: string;
        WidgetID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid username or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked (idempotent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Logged out */
                        message: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active providers and whether local password login is offered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        providers: components["schemas"]["PublicProvider"][];
                        localAuthEnabled: boolean;
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    oidcLogin: {
        parameters: {
            query?: {
                /**
                 * @description Origin to return to after login (validated against the CORS
                 *     allowlist; used by the cross-origin widget-test portal).
                 */
                return_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the IdP authorization endpoint. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidcCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back to the app with `#token=…` on success. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidcLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the IdP end-session endpoint (or straight back to the app). */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidcBackchannelLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Signed JWT per the Back-Channel Logout spec. */
                    logout_token: string;
                };
            };
        };
        responses: {
            /** @description Logout token accepted (returned even when no local session matched). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or missing logout_token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID, username, or search term. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user (full or limited view depending on the caller's role). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"] | components["schemas"]["UserLimited"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID, username, or search term. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    firstName?: string;
                    lastName?: string;
                    /** @description Must contain "@". */
                    email?: string;
                    password?: string;
                };
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's keys (plaintext key is never included). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /**
                     * Format: date-time
                     * @description Optional expiry; omit or null for a non-expiring key.
                     */
                    expiresAt?: string | null;
                };
            };
        };
        responses: {
            /** @description Key created. Store `key` now — it cannot be retrieved again. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"] & {
                        /**
                         * @description The full plaintext key. Shown only in this response.
                         * @example jrag_9f86d081884c7d659a2feaa0c55ad015
                         */
                        key: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All agents, as stored (full JSON objects). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents: components["schemas"]["Agent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    upsertAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Agent"];
            };
        };
        responses: {
            /** @description The stored agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The agent is still referenced by one or more widgets. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listWidgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All widgets, as stored (full JSON objects). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        widgets: components["schemas"]["Widget"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getPublicWidgetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WidgetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The public widget configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetPublicConfig"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    upsertWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WidgetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Widget"];
            };
        };
        responses: {
            /** @description The stored widget. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WidgetID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Widget deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    widgetChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WidgetID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    messages: components["schemas"]["ChatMessage"][];
                    /** @default false */
                    stream?: boolean;
                };
            };
        };
        responses: {
            /**
             * @description Non-streaming: a single JSON reply. Streaming: an SSE stream of
             *     `data: {"content": "…"}` chunks terminated by
             *     `data: {"done": true, "finishReason": …}`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The widget is paused. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Per-IP rate limit exceeded (Retry-After is set). */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models available at the upstream endpoint. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        models: components["schemas"]["ModelInfo"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["NotConfigured"];
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Upstream model id. Either `model` or `knowledgeBaseId` is required. */
                    model?: string;
                    /** @description Legacy alias for `model`. */
                    knowledgeBaseId?: string;
                    messages: components["schemas"]["ChatMessage"][];
                    /** @description Optional completion token cap. */
                    maxTokens?: number;
                    /** @default false */
                    stream?: boolean;
                };
            };
        };
        responses: {
            /**
             * @description Non-streaming: a single JSON reply. Streaming: an SSE stream of
             *     `data: {"content": "…"}` chunks terminated by
             *     `data: {"done": true, "finishReason": …}`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["NotConfigured"];
        };
    };
}
